# Generated by Django 4.2 on 2024-02-10 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advertising_company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PotentialClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "phone",
                    models.PositiveIntegerField(unique=True, verbose_name="Телефон"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                (
                    "advertising_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="potential_clients",
                        to="advertising_company.advertisingcompany",
                        verbose_name="Рекламная компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Потенциальный клиент",
                "verbose_name_plural": "Потенциальные клиенты",
                "ordering": ["full_name"],
            },
        ),
    ]
