# Generated by Django 4.2 on 2024-02-10 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contract", "0001_initial"),
        ("passive_client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_clients",
                        to="contract.contract",
                        verbose_name=" Контракт",
                    ),
                ),
                (
                    "potential_client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passive_client.potentialclient",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Активный клиент",
                "verbose_name_plural": "Активные клиенты",
                "ordering": ["potential_client__full_name"],
            },
        ),
    ]
